services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: dev
      args:
        USER_ID: ${UID:-1001}
        GROUP_ID: ${GID:-1001}
    user: "www-data:www-data"
    volumes:
      - .:/var/www/html
      # - /var/www/html/vendor
      - ./docker/api/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PHP_IDE_CONFIG: "serverName=php-invoice-server"

  api_nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/api/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
